Use Company_SD
GO
--1
-- Female dependents of female employees
SELECT d.DEPENDENT_NAME, d.SEX
FROM DEPENDENT d
JOIN EMPLOYEE e ON d.ESSN = e.SSN
WHERE d.SEX = 'F' AND e.SEX = 'F'

UNION

-- Male dependents of male employees
SELECT d.DEPENDENT_NAME, d.SEX
FROM DEPENDENT d
JOIN EMPLOYEE e ON d.ESSN = e.SSN
WHERE d.SEX = 'M' AND e.SEX = 'M';

--2
SELECT p.PNAME, SUM(w.HOURS) AS TOTAL_HOURS_PER_WEEK
FROM PROJECT p
LEFT JOIN WORKS_for w ON p.PNUMBER = w.PNO
GROUP BY p.PNAME;

--3
SELECT d.*
FROM DEPARTMENTs d
JOIN EMPLOYEE e ON d.DNUM = e.DNO
WHERE e.SSN = (SELECT MIN(SSN) FROM EMPLOYEE);

--4
SELECT d.DNAME, 
       MAX(e.SALARY) AS MAX_SALARY,
       MIN(e.SALARY) AS MIN_SALARY,
       ISNULL(AVG(e.SALARY), 0) AS AVG_SALARY
FROM DEPARTMENTs d
LEFT JOIN EMPLOYEE e ON d.DNUM = e.DNO
GROUP BY d.DNAME;

--5
SELECT CONCAT(e.FNAME, ' ', e.LNAME) AS MANAGER_NAME
FROM EMPLOYEE e
JOIN DEPARTMENTs d ON e.SSN = d.MGRSSN
WHERE NOT EXISTS (
    SELECT 1 FROM DEPENDENT dep WHERE dep.ESSN = e.SSN
);

--6
SELECT d.DNUM, d.DNAME, COUNT(e.SSN) AS EMPLOYEE_COUNT
FROM DEPARTMENTs d
LEFT JOIN EMPLOYEE e ON d.DNUM = e.DNO
GROUP BY d.DNUM, d.DNAME
HAVING ISNULL(AVG(e.SALARY), 0) < (SELECT ISNULL(AVG(SALARY), 0) FROM EMPLOYEE);

--7
SELECT CONCAT(e.FNAME, ' ', e.LNAME) AS EMPLOYEE_NAME, p.PNAME
FROM EMPLOYEE e
JOIN Works_for w ON e.SSN = w.ESSN
JOIN PROJECT p ON w.PNO = p.PNUMBER
JOIN DEPARTMENTs d ON e.DNO = d.DNUM
ORDER BY d.DNUM, e.LNAME, e.FNAME;

--8
SELECT FNAME, LNAME, SALARY
FROM EMPLOYEE
WHERE SALARY IN (
    SELECT DISTINCT TOP 2 SALARY 
    FROM EMPLOYEE 
    ORDER BY SALARY DESC
)
ORDER BY SALARY DESC;

--9
SELECT CONCAT(e.FNAME, ' ', e.LNAME) AS EMPLOYEE_NAME
FROM EMPLOYEE e
WHERE EXISTS (
    SELECT 1 
    FROM DEPENDENT d 
    WHERE d.DEPENDENT_NAME = e.FNAME OR d.DEPENDENT_NAME = e.LNAME
);

--10
SELECT e.SSN, CONCAT(e.FNAME, ' ', e.LNAME) AS EMPLOYEE_NAME
FROM EMPLOYEE e
WHERE EXISTS (
    SELECT 1 FROM DEPENDENT d WHERE d.ESSN = e.SSN
);

--11
DECLARE @NewSSN CHAR(9) = '112233444';

INSERT INTO EMPLOYEE (FNAME, LNAME, SSN, BDATE, ADDRESS, SEX, SALARY, SUPERSSN, DNO)
VALUES ('IT', 'Manager', @NewSSN, '1975-01-01', '123 IT St', 'M', 70000, NULL, NULL);

INSERT INTO Departments(Dname, Dnum, MgrSSN, [MGRStart Date])
VALUES ('DEPT IT', 100, @NewSSN, '2006-11-01');

UPDATE EMPLOYEE SET DNO = 100 WHERE SSN = @NewSSN;

--12
-- a.
UPDATE DEPARTMENTs 
SET MGRSSN = '968574', [MGRSTART DATE] = GETDATE() 
WHERE DNUM = 100;

-- b.
UPDATE DEPARTMENTs 
SET MGRSSN = '102672', [MGRSTART DATE] = GETDATE() 
WHERE DNUM = 20;

-- c.
UPDATE EMPLOYEE
SET SUPERSSN = '102672'
WHERE SSN = '102660';

--13
DELETE FROM DEPENDENT WHERE ESSN = '223344';
DELETE FROM WORKS_for WHERE ESSN = '223344';
UPDATE DEPARTMENTs SET MGRSSN = '102672' WHERE MGRSSN = '223344';
UPDATE EMPLOYEE SET SUPERSSN = '102672' WHERE SUPERSSN = '223344';
DELETE FROM EMPLOYEE WHERE SSN = '223344';

--14
UPDATE EMPLOYEE
SET Salary = Salary * 1.3
WHERE SSN IN (
    SELECT ESSN
    FROM Works_for W
    JOIN PROJECT P ON W.Pno = P.Pnumber
    WHERE P.Pname = 'Al Rabwah'
);